# this is a test in which the second subjob fails to submit because of the runtime handler exception
from GangaTest.Framework.utils import assert_cannot_submit
j = Job()
j.backend = TestSubmitter()
j.application = TestApplication()
j.splitter = GenericSplitter()
j.splitter.attribute = 'application.fail'
j.splitter.values = ['','prepare','']

assert_cannot_submit(j)
assert(len(j.subjobs)==0)
